sonar.projectKey=gerard-test_EjemploSonarQube
sonar.organization=gerard-test

sonar.sources=src

sonar.java.binaries=target/classes

# Excluir archivos generados
sonar.exclusions=target/**

# Excluir duplicaciones
sonar.cpd.exclusions=target/**

