sonar.projectKey=ChristianRTD_MiNuevaApp
sonar.organization=christianrtd

sonar.sources=src

sonar.java.binaries=target/classes

# Excluir archivos generados
sonar.exclusions=target/**

# Excluir duplicaciones
sonar.cpd.exclusions=target/**

